version: '3.8'

services:
  portfolio-inc-var-api:
    image: node:16-alpine3.14
    volumes:
      - .:/home/node/portfolio-inc-var-api
    
    command: sh -c "cd /home/node/portfolio-inc-var-api && yarn install  && npx prisma migrate dev  && yarn run test:ci && yarn run test:e2e"
    env_file:
    - test.env
    user: root

    depends_on:
      - "db"

  db:
    image: postgres
    volumes:
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
 