name: portfolio-inc-var-api CI
on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master, develop ]

env:
  NODE_ENV: test

jobs:
  test:
    name: Run All tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: run ci in containers
        run: docker-compose -f docker-compose.test.yml run portfolio-inc-var-api

  push_to_registry:
    if: github.ref == 'refs/heads/master'
    needs: test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: gaugau3000/portfolio-inc-var-api:latest
